# Generated by Django 2.0 on 2018-04-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ums', '0002_auto_20180403_0519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='grades',
        ),
        migrations.AddField(
            model_name='student',
            name='gra_des',
            field=models.CharField(blank=True, default=' ', max_length=100, verbose_name='题目'),
        ),
    ]
