# Generated by Django 2.0 on 2018-04-03 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ums', '0003_auto_20180403_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gra_des',
            field=models.CharField(blank=True, default='未选', max_length=100, verbose_name='毕设题目'),
        ),
    ]
