# Generated by Django 2.0 on 2018-04-03 05:19

from django.db import migrations, models
import edms.file_storage.file_storage


class Migration(migrations.Migration):

    dependencies = [
        ('edms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradesfiles',
            name='addition',
            field=models.FileField(blank=True, storage=edms.file_storage.file_storage.FileStorage(), upload_to='uploads/GraDesFiles/%Y/%m/%d', verbose_name='附件(设计图纸，软件等)'),
        ),
        migrations.AlterField(
            model_name='gradesfiles',
            name='begin_report',
            field=models.FileField(blank=True, storage=edms.file_storage.file_storage.FileStorage(), upload_to='uploads/GraDesFiles/%Y/%m/%d', verbose_name='开题报告'),
        ),
        migrations.AlterField(
            model_name='gradesfiles',
            name='check_table',
            field=models.FileField(blank=True, storage=edms.file_storage.file_storage.FileStorage(), upload_to='uploads/GraDesFiles/%Y/%m/%d', verbose_name='考核表'),
        ),
        migrations.AlterField(
            model_name='gradesfiles',
            name='paper',
            field=models.FileField(blank=True, storage=edms.file_storage.file_storage.FileStorage(), upload_to='uploads/GraDesFiles/%Y/%m/%d', verbose_name='毕业设计(论文)'),
        ),
        migrations.AlterField(
            model_name='gradesfiles',
            name='project_training',
            field=models.FileField(blank=True, storage=edms.file_storage.file_storage.FileStorage(), upload_to='uploads/GraDesFiles/%Y/%m/%d', verbose_name='实习手册'),
        ),
        migrations.AlterField(
            model_name='gradesfiles',
            name='summary',
            field=models.FileField(blank=True, storage=edms.file_storage.file_storage.FileStorage(), upload_to='uploads/GraDesFiles/%Y/%m/%d', verbose_name='文献综述'),
        ),
        migrations.AlterField(
            model_name='gradesfiles',
            name='task',
            field=models.FileField(blank=True, storage=edms.file_storage.file_storage.FileStorage(), upload_to='uploads/GraDesFiles/%Y/%m/%d', verbose_name='任务书'),
        ),
        migrations.AlterField(
            model_name='gradesfiles',
            name='task_record',
            field=models.FileField(blank=True, storage=edms.file_storage.file_storage.FileStorage(), upload_to='uploads/GraDesFiles/%Y/%m/%d', verbose_name='指导记录'),
        ),
        migrations.AlterField(
            model_name='gradesfiles',
            name='translation',
            field=models.FileField(blank=True, storage=edms.file_storage.file_storage.FileStorage(), upload_to='uploads/GraDesFiles/%Y/%m/%d', verbose_name='外文翻译(附原文)'),
        ),
        migrations.AlterField(
            model_name='teachfiles',
            name='exam_make_up',
            field=models.FileField(blank=True, storage=edms.file_storage.file_storage.FileStorage(), upload_to='uploads/TeachFiles/%Y/%m/%d', verbose_name='补考试卷样卷'),
        ),
        migrations.AlterField(
            model_name='teachfiles',
            name='exam_make_up_answer',
            field=models.FileField(blank=True, storage=edms.file_storage.file_storage.FileStorage(), upload_to='uploads/TeachFiles/%Y/%m/%d', verbose_name='补考试卷答案及评分标准'),
        ),
        migrations.AlterField(
            model_name='teachfiles',
            name='exam_make_up_part',
            field=models.FileField(blank=True, storage=edms.file_storage.file_storage.FileStorage(), upload_to='uploads/TeachFiles/%Y/%m/%d', verbose_name='补考部分'),
        ),
        migrations.AlterField(
            model_name='teachfiles',
            name='exam_paper',
            field=models.FileField(blank=True, storage=edms.file_storage.file_storage.FileStorage(), upload_to='uploads/TeachFiles/%Y/%m/%d', verbose_name='正考试卷样卷'),
        ),
        migrations.AlterField(
            model_name='teachfiles',
            name='exam_paper_analyze',
            field=models.FileField(blank=True, storage=edms.file_storage.file_storage.FileStorage(), upload_to='uploads/TeachFiles/%Y/%m/%d', verbose_name='试卷分析'),
        ),
        migrations.AlterField(
            model_name='teachfiles',
            name='exam_paper_answer',
            field=models.FileField(blank=True, storage=edms.file_storage.file_storage.FileStorage(), upload_to='uploads/TeachFiles/%Y/%m/%d', verbose_name='正考试卷答案及评分标准'),
        ),
        migrations.AlterField(
            model_name='teachfiles',
            name='exam_part',
            field=models.FileField(blank=True, storage=edms.file_storage.file_storage.FileStorage(), upload_to='uploads/TeachFiles/%Y/%m/%d', verbose_name='正考部分'),
        ),
        migrations.AlterField(
            model_name='teachfiles',
            name='student_score',
            field=models.FileField(blank=True, storage=edms.file_storage.file_storage.FileStorage(), upload_to='uploads/TeachFiles/%Y/%m/%d', verbose_name='学生成绩登记册'),
        ),
        migrations.AlterField(
            model_name='teachfiles',
            name='teaching_plan',
            field=models.FileField(blank=True, storage=edms.file_storage.file_storage.FileStorage(), upload_to='uploads/TeachFiles/%Y/%m/%d', verbose_name='教学计划'),
        ),
        migrations.AlterField(
            model_name='teachfiles',
            name='teaching_sum_up',
            field=models.FileField(blank=True, storage=edms.file_storage.file_storage.FileStorage(), upload_to='uploads/TeachFiles/%Y/%m/%d', verbose_name='教学小结表'),
        ),
        migrations.AlterField(
            model_name='teachfiles',
            name='teaching_syllabus',
            field=models.FileField(blank=True, storage=edms.file_storage.file_storage.FileStorage(), upload_to='uploads/TeachFiles/%Y/%m/%d', verbose_name='教学大纲'),
        ),
    ]
