# Generated by Django 2.0 on 2018-03-27 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edms', '0002_auto_20180326_0755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gradesfiles',
            old_name='name',
            new_name='graduation_thesis',
        ),
    ]
